# Generated by Django 4.2.7 on 2025-10-10 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], max_length=20)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=255)),
                ('payment_token', models.CharField(blank=True, help_text='Tokenized payment method ID', max_length=255)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='customers.customer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_active'], name='payments_pa_custome_061a80_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('rental_payment', 'Rental Payment'), ('security_deposit', 'Security Deposit'), ('late_fee', 'Late Fee'), ('damage_fee', 'Damage Fee'), ('additional_service', 'Additional Service'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('external_payment_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rental')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'), models.Index(fields=['rental', 'payment_type'], name='payments_pa_rental__c1faf0_idx'), models.Index(fields=['customer', 'status'], name='payments_pa_custome_25a299_idx'), models.Index(fields=['status', 'payment_date'], name='payments_pa_status_3f89d4_idx')],
            },
        ),
    ]
