# Generated by Django 4.2.7 on 2025-10-10 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pickup_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('actual_pickup_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('additional_fees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('deposit_refund_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_mileage', models.IntegerField(default=0)),
                ('return_mileage', models.IntegerField(blank=True, null=True)),
                ('pickup_fuel_level', models.CharField(default='Full', max_length=20)),
                ('return_fuel_level', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('pickup_notes', models.TextField(blank=True)),
                ('return_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('pickup_staff', models.CharField(blank=True, max_length=255)),
                ('return_staff', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rental_id'], name='rentals_ren_rental__660f22_idx'), models.Index(fields=['customer', 'status'], name='rentals_ren_custome_a8e224_idx'), models.Index(fields=['car', 'pickup_date'], name='rentals_ren_car_id_f9459e_idx'), models.Index(fields=['status', 'pickup_date'], name='rentals_ren_status_945d9b_idx')],
            },
        ),
    ]
